// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdJU_JYufzynJ5Mhr37IR_YYSSPInu-wg',
    appId: '1:370393791008:web:ef8193340e5f904cb1da45',
    messagingSenderId: '370393791008',
    projectId: 'mcq-test-75190',
    authDomain: 'mcq-test-75190.firebaseapp.com',
    storageBucket: 'mcq-test-75190.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnzF_xV2lCDEhn7165jKDIlrfAvrOdWZc',
    appId: '1:370393791008:android:1aa13db1530b9137b1da45',
    messagingSenderId: '370393791008',
    projectId: 'mcq-test-75190',
    storageBucket: 'mcq-test-75190.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLWnSq9lheNVaMhEeynwAO-pFe2hcSIcs',
    appId: '1:370393791008:ios:ccd1f36d04bb87eab1da45',
    messagingSenderId: '370393791008',
    projectId: 'mcq-test-75190',
    storageBucket: 'mcq-test-75190.appspot.com',
    iosBundleId: 'com.example.mcqTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLWnSq9lheNVaMhEeynwAO-pFe2hcSIcs',
    appId: '1:370393791008:ios:ccd1f36d04bb87eab1da45',
    messagingSenderId: '370393791008',
    projectId: 'mcq-test-75190',
    storageBucket: 'mcq-test-75190.appspot.com',
    iosBundleId: 'com.example.mcqTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdJU_JYufzynJ5Mhr37IR_YYSSPInu-wg',
    appId: '1:370393791008:web:c70836f78d796293b1da45',
    messagingSenderId: '370393791008',
    projectId: 'mcq-test-75190',
    authDomain: 'mcq-test-75190.firebaseapp.com',
    storageBucket: 'mcq-test-75190.appspot.com',
  );
}
